# Generated by Django 4.0.3 on 2022-03-19 21:25

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_job_parent_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='aboutus',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.job'),
        ),
        migrations.AlterField(
            model_name='job',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='home.company'),
        ),
    ]
