# Generated by Django 4.0.3 on 2022-03-20 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_contactmessage_faq'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FAQ',
        ),
    ]
