# Generated by Django 4.0.3 on 2022-03-20 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_delete_faq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
    ]
