# Generated by Django 4.0.3 on 2022-03-23 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_rename_job_jobs'),
        ('company', '0003_rename_company_companies'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Companies',
            new_name='Company',
        ),
    ]
