# Generated by Django 4.0.3 on 2022-04-13 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_company_city_company_employers_company_sector_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, default='images/logo.png', upload_to='images/'),
        ),
    ]
