# Generated by Django 4.0.3 on 2022-04-15 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_alter_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='city',
            field=models.CharField(blank=True, choices=[('İstanbul', 'İstanbul'), ('Ankara', 'Ankara'), ('İzmir', 'İzmir'), ('Kocaeli', 'Kocaeli'), ('Bursa', 'Bursa'), ('Şanlıurfa', 'Şanlıurfa')], max_length=50),
        ),
    ]
