# Generated by Django 4.0.3 on 2022-05-17 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_alter_company_address_alter_company_auth_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyphotogallery',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
    ]
