# Generated by Django 4.0.3 on 2022-05-21 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_alter_companyphotogallery_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, default='images/logo.png', upload_to='images/'),
        ),
    ]
