# Generated by Django 4.0.3 on 2022-05-29 17:49

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_alter_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='about_company',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='companyphotogallery',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
