# Generated by Django 4.0.3 on 2022-04-08 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(default=55, max_length=30),
            preserve_default=False,
        ),
    ]
