# Generated by Django 4.0.3 on 2022-04-10 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_userprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='presentation',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
