# Generated by Django 4.0.3 on 2022-04-11 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0008_usereducation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usereducation',
            name='user_profile',
        ),
        migrations.AddField(
            model_name='usereducation',
            name='user',
            field=models.ForeignKey(default=111, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
