# Generated by Django 4.0.3 on 2022-05-29 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_userprofile_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='rate',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='images/users/user.png', upload_to='images/users/'),
        ),
    ]
