# Generated by Django 4.0.3 on 2022-05-29 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_userprofile_rate_alter_userprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='rate_count',
            field=models.FloatField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='rate',
            field=models.FloatField(blank=True, default=1),
        ),
    ]
