# Generated by Django 4.0.3 on 2022-05-29 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_userprofile_rate_count_alter_userprofile_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='rate_count',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
