# Generated by Django 4.0.3 on 2022-03-23 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_rename_company_companies'),
        ('job', '0006_job_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Job',
            new_name='Jobs',
        ),
    ]
