# Generated by Django 4.0.3 on 2022-03-23 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_rename_companies_company'),
        ('job', '0007_rename_job_jobs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jobs',
            new_name='Job',
        ),
    ]
