# Generated by Django 4.0.3 on 2022-04-14 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_rename_jobs_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='profession',
            new_name='title',
        ),
        migrations.AddField(
            model_name='job',
            name='education_level',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='experience',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='gender',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
