# Generated by Django 4.0.3 on 2022-04-23 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0011_alter_job_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='gender',
            field=models.CharField(choices=[('Farketmez', 'Farketmez'), ('Erkek', 'Erkek'), ('Kadın', 'Kadın')], max_length=30),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time'), ('Freelance', 'Freelance'), ('Remote', 'Remote')], max_length=30),
        ),
    ]
