# Generated by Django 4.0.3 on 2022-05-17 21:11

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0015_alter_job_education_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='get_slug', unique=True),
        ),
    ]
